version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: madhaviag/reverseproxy-v2
  backend_user:
    build:
      context: ../../udagram-backend-user
    image: madhaviag/udagram-user-v2
  backend_feed:
    build:
      context: ../../udagram-backend-feed
    image: madhaviag/udagran-feed-v2
  frontend:
    build:
      context: ../../udagram-frontend  
    image: madhaviag/udagram-frontend-v2
